### PR TITLE
BUG: Fix `itk::AttenuationImageFilter` region threading

### LINKED ISSUE #185: Threading issue in Attenuation filter with TBB MultiThreader
Trying to run example https://github.com/KitwareMedical/ITKUltrasound/blob/master/examples/RFPowerSpectraAttenuation.ipynb locally, with up to date ITKUltrasound at 814944b9d9184478241bf438054c8486e998fd38 the "Metric Image of Attenuations in Liver" and its accompanying mask change from run to run, and all look wrong. Example:
Screenshot 2022-03-11 17 22 36

The result looks as expected if the following line is added right after filter instantiation:
```py
attenuation_filter.SetNumberOfWorkUnits(1)
```

### PR DESCRIPTION
**Pull request by tbirdso**
Disables dynamic threading to enforce same-size regions and correctly
use the image region splitter to enforce continuity along scan lines.

Closes #185.

### CODE REVIEW

**Comment by tbirdso** [comment]
Note that simply changing to `DynamicMultiThreadingOff` returns an error:
```
4: Trying attenuationFilter->Update()
4:
4: itk::ExceptionObject (000000B5720FF1A0)
4: Location: "unknown"
4: File: C:\repos\ITK\Modules\Core\Common\include\itkImageSource.hxx
4: Line: 258
4: Description: ITK ERROR: AttenuationImageFilter(000001D92B98DB20): With DynamicMultiThreadingOff subclass should override this method. The signature of ThreadedGenerateData() has been changed in ITK v4 to use the new ThreadIdType.
```

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
> Note that simply changing to DynamicMultiThreadingOff returns an error

This PR seems to pass tests.

> simply changing to DynamicMultiThreadingOff

What does this mean? How is it different from the change proposed here?

**Comment by tbirdso** [comment]
It looks like the issue stemmed from relying on `DynamicThreadedGenerateData` after turning off dynamic threading. I am unclear on why the error was not reflected in CI. Tests are now passing locally.

**Comment by tbirdso** [comment]
Note that Github Actions is having trouble today (see [https://www.githubstatus.com/](https://www.githubstatus.com/)), maybe that had something to do with tests passing where they should have failed? That makes me nervous about merging any changes until CI functionality resumes.

File: include/itkAttenuationImageFilter.hxx [hunk 1]
```diff
@@ -126,8 +126,9 @@ AttenuationImageFilter<TInputImage, TOutputImage, TMaskImage>::BeforeThreadedGen
 
 template <typename TInputImage, typename TOutputImage, typename TMaskImage>
 void
-AttenuationImageFilter<TInputImage, TOutputImage, TMaskImage>::DynamicThreadedGenerateData(
-  const OutputRegionType & regionForThread)
+AttenuationImageFilter<TInputImage, TOutputImage, TMaskImage>::ThreadedGenerateData(
+  const OutputImageRegionType & regionForThread,
+  ThreadIdType                  threadId)
```
Comment (dzenanz) [inline include/itkAttenuationImageFilter.hxx:131]: As `threadId` parameter is not used, we should remove its name to avoid unused variable warning:
```suggestion
  ThreadIdType)
```

**Review by dzenanz — APPROVED** [review]

File: include/itkAttenuationImageFilter.hxx (hunk 1 above)
Comment (tbirdso) [reply include/itkAttenuationImageFilter.hxx]: Resolved in forced update.

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
Amended the commit message and did a force-push to get CI running on this again.

**Comment by tbirdso** [comment]
Pushed fix for [CDash compiler error](https://open.cdash.org/viewBuildError.php?buildid=7799860):
>include/itkAttenuationImageFilter.h:208:30: error: 'OutputImageRegionType' does not name a type; did you mean 'OutputRegionType'?

Unclear on why this compiled on Windows if the type was not defined 😕

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
